name: bold
description: A game of bluffing and reasoning.
publish_to: 'none' 
version: 1.3.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  flutter_native_splash: ^2.3.5
  flutter_translate: ^4.0.4
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/i18n/

flutter_native_splash:
  color: "#000000"
  # background_image: "assets/neutral_flower.png"
  image: assets/neutral_flower.png
  color_dark: "#000000"
  #image_dark: assets/neutral_flower.png
  
  android_12:
    image: assets/neutral_flower.png
    color: "#42a5f5"
    image_dark: assets/neutral_flower.png
    color_dark: "#000000"